language: java
install: true
script: mvn -P web,prod verify
jdk:
  - oraclejdk8
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $TRAVIS_BUILD_DIR/web/node_modules
    - $TRAVIS_BUILD_DIR/web/typings
    - $TRAVIS_BUILD_DIR/web/node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
      secure: "$GITHUB_DEPLOY_TOKEN"
  file:
     $TRAVIS_BUILD_DIR/core/target/zombieCore.jar
  on:
    tags: true
    
notifications:
  email: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "$COVERITY_SECURE"

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "patexoid/ZombieLib2"
      description: "Build submitted via Travis CI"
    notification_email: patexoid@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn compile"
    branch_pattern: coverity_scan
